name: Configure Azure VM

on:
  workflow_dispatch:

jobs:
  configure:
    runs-on: ubuntu-latest
    env:
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Get VM Public IP
        working-directory: ./terraform
        id: ip
        run: |
          echo "VM_IP=$(terraform output -raw vm_public_ip)" >> $GITHUB_ENV

    #   - name: Install Ansible
    #     run: sudo apt-get update && sudo apt-get install -y ansible

      - name: Install Ansible 2.17
        run: |
          python3 -m pip install --upgrade pip
          pip install "ansible-core==2.17.*"

      - name: Check Ansible version
        run: ansible --version

      - name: Add SSH private key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Create Ansible inventory
        working-directory: ./ansible
        run: |
          echo "[azure_vm]" > inventory.ini
          echo "$VM_IP ansible_user=azureuser ansible_ssh_private_key_file=/github/home/.ssh/id_rsa" >> inventory.ini

      # - name: Write SSH key to file
      #   run: |
      #     mkdir -p ~/.ssh
      #     echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
      #     chmod 600 ~/.ssh/id_rsa

      # - name: Create Ansible inventory
      #   working-directory: ./ansible
      #   run: |
      #     echo "[azure_vm]" > inventory.ini
      #     echo "$VM_IP ansible_user=azureuser" >> inventory.ini

      - name: Check Ansible inventory file
        working-directory: ./ansible
        run: cat inventory.ini

      - name: Run Ansible Playbook
        working-directory: ./ansible
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
          OAUTH2_COOKIE_SECRET: ${{ secrets.OAUTH2_COOKIE_SECRET }}
        run: ansible-playbook -i inventory.ini playbook.yml
